version: '3.8'

x-app-service: &default-app
  build: .
  command: ''
  environment:
    - MONGO_URL=mongodb://mongo:27017/my-collection
  depends_on:
    - mongo
  volumes:
    - .:/code

services:

  backend-planetdataset:
    <<: *default-app
    command: bash -c "npm run build && npm run build:tsc && npm run dev"
    ports:
      - 3000:3000

  mongo:
    image: mongo:3.4.6
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017

volumes:
  esdata:
    driver: local
